# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='lightweightemail',
        #     name='body',
        #     field=models.BinaryField(verbose_name='Body'),
        # ),
        migrations.AddField(
                model_name='lightweightemail',
                name='body_tmp',
                field=models.TextField(default='', verbose_name='Body'),
                preserve_default=False,
        ),
    ]
