# Generated by Django 4.2 on 2023-04-05 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='persons__contact__default_lv',
            old_fields=('last_name', 'first_name', 'cremeentity_ptr'),
        ),
        migrations.RenameIndex(
            model_name='organisation',
            new_name='persons__orga__default_lv',
            old_fields=('name', 'cremeentity_ptr'),
        ),
    ]
