# Generated by Django 5.0.9 on 2024-09-19 09:22
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0029_v2_7__floating_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
