# Generated by Django 5.1.4 on 2025-01-14 10:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_v2_7__floating_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfigitem',
            name='view_day_end',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='View end'),
        ),
        migrations.AddField(
            model_name='calendarconfigitem',
            name='view_day_start',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='View start'),
        ),
    ]
