# Generated by Django 5.1.4 on 2025-02-10 14:28

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_v2_7__floating_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfigitem',
            name='view_day_end',
            field=models.TimeField(default=datetime.time(0, 0), help_text='End of the displayed hours.\nCan be different from the day range that restricts the moves and creation of events', verbose_name='View end'),
        ),
        migrations.AddField(
            model_name='calendarconfigitem',
            name='view_day_start',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Start of the displayed hours.\nCan be different from the day range that restricts the moves and creation of events', verbose_name='View start'),
        ),
    ]
