# Generated by Django 5.2.3 on 2025-07-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_v2_7__calendarconfigitem_view_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfigitem',
            name='allow_event_anyday',
            field=models.BooleanField(default=True, verbose_name='Allow events on all days'),
        ),
        migrations.AddField(
            model_name='calendarconfigitem',
            name='allow_event_overtime',
            field=models.BooleanField(default=True, verbose_name='Allow events outside business hours of a day'),
        ),
    ]
