# -*- coding: utf-8 -*-

CREME_EMAIL = "" 
CREME_EMAIL_SERVER  = "" 
CREME_EMAIL_USERNAME  = ""
CREME_EMAIL_PASSWORD  = ""
CREME_EMAIL_PORT = 25

CREME_SAMOUSSA_URL = 'http://localhost:8001/'
CREME_SAMOUSSA_USERNAME = 'compte21'
CREME_SAMOUSSA_PASSWORD = 'compte21'
