# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 14:47
from __future__ import unicode_literals

from django.db import migrations
from django.db.models.deletion import CASCADE

from creme.creme_core.models.fields import CTypeForeignKey


class Migration(migrations.Migration):
    dependencies = [
        ('crudity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitingaction',
            old_name='data',
            new_name='raw_data',
        ),
        migrations.AlterField(
            model_name='waitingaction',
            name='ct',
            field=CTypeForeignKey(on_delete=CASCADE, to='contenttypes.ContentType', verbose_name='Type of resource'),
        ),
    ]
