# Generated by Django 3.2.12 on 2022-02-08 16:07

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import creme.creme_api.models
import creme.creme_core.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('client_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, verbose_name='Client secret')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('token_duration', models.IntegerField(default=3600, help_text='Number of seconds during which tokens will be valid. It will only affect newly created tokens.', verbose_name='Tokens duration')),
                ('created', creme.creme_core.models.fields.CreationDateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
                ('modified', creme.creme_core.models.fields.ModificationDateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Last modification')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=creme.creme_api.models.default_token_code, max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('created', creme.creme_core.models.fields.CreationDateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', creme.creme_core.models.fields.ModificationDateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creme_api.application')),
            ],
        ),
    ]
