# Generated by Django 2.2.16 on 2020-09-23 11:05

import django.utils.timezone
from django.db import migrations, models

import creme.creme_core.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', creme.creme_core.models.fields.CreationDateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
                ('modified', creme.creme_core.models.fields.ModificationDateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Last modification')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='Key')),
                ('last_use', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last use')),
            ],
            options={
                'verbose_name': 'Api key',
                'verbose_name_plural': 'Api keys',
            },
        ),
    ]
