from .base import AppTestCase
from .invoice import *
from .quote import *
from .credit_note import *
from .sales_order import *
from .templatebase import *
from .line import *
from .payment_information import *
from .convert import *
from .function_fields import *
