# Generated by Django 3.2.12 on 2022-05-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='trigger_offset',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='trigger_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Trigger date'),
        ),
    ]
