# Generated by Django 5.0.9 on 2024-09-19 09:56
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0041_v2_7__number_generation03'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='creditnotestatus',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quotestatus',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorderstatus',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='settlementterms',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        # migrations.AlterField(
        #     model_name='templatebase',
        #     name='status_uuid',
        #     field=models.UUIDField(editable=False),
        # ),
    ]
