# Generated by Django 2.2.7 on 2019-11-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0016_v2_1__convert_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyers_order_number',
            field=models.CharField(blank=True, help_text="Number of buyer's order (french legislation)", max_length=100, verbose_name="Buyer's order"),
        ),
    ]
