# Generated by Django 4.0.10 on 2023-02-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_v2_5__colored_statuses02'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
