# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0040_v1_8__sandbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cremeentity',
            name='is_actived',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='is_actived',
        ),
    ]
