# Generated by Django 2.2 on 2019-06-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0055_v2_1__cremeentity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brickstate',
            name='json_extra_data',
            field=models.TextField(default='{}', editable=False),
        ),
    ]
