# Generated by Django 2.2.9 on 2020-01-31 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0063_v2_2__setcreds_null_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationtype',
            name='object_ctypes',
        ),
        migrations.RemoveField(
            model_name='relationtype',
            name='object_properties',
        ),
    ]
