# Generated by Django 2.2.11 on 2020-04-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0066_v2_2__customfield_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancebrickconfigitem',
            name='verbose',
        ),
        migrations.AddField(
            model_name='instancebrickconfigitem',
            name='brick_class_id',
            field=models.CharField(default='', editable=False, max_length=300, verbose_name='Block class ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancebrickconfigitem',
            name='json_extra_data',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='instancebrickconfigitem',
            name='entity',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='creme_core.CremeEntity', verbose_name='Block related entity'),
        ),
    ]
