# Generated by Django 2.2.11 on 2020-04-06 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0068_v2_2__instancebricks_json_data02'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancebrickconfigitem',
            name='brick_id',
        ),
        migrations.RemoveField(
            model_name='instancebrickconfigitem',
            name='data',
        ),
    ]
