# Generated by Django 2.2.15 on 2020-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0071_v2_2__new_customfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonmenuitem',
            name='tmp_id',
            field=models.IntegerField(null=True),
        ),
    ]
