# Generated by Django 2.2.15 on 2020-08-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0073_v2_2__buttonmenuitem_int_id02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmenuitem',
            name='tmp_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        # ---
        migrations.RemoveField(
            model_name='buttonmenuitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='buttonmenuitem',
            name='tmp_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        # ---
        migrations.AlterField(
            model_name='buttonmenuitem',
            name='tmp_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        # ---
        migrations.RenameField(
            model_name='buttonmenuitem',
            old_name='tmp_id',
            new_name='id',
        ),
    ]
