# Generated by Django 3.2 on 2021-05-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0078_v2_2__menuconfigitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconfigitem',
            name='json_cells',
            field=models.JSONField(default=list, editable=False),
        ),
    ]
