# Generated by Django 3.2.12 on 2022-03-14 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0101_v2_4__relation_brick_ids01'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationbrickitem',
            name='brick_id',
        ),
    ]
