# Generated by Django 3.2.12 on 2022-05-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0107_v2_4__worldsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brickstate',
            name='json_extra_data',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='custombrickconfigitem',
            name='json_cells',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='instancebrickconfigitem',
            name='json_extra_data',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='relationbrickitem',
            name='json_cells_map',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
