# Generated by Django 3.2.12 on 2022-05-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0110_v2_4__customformconfigitem_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtype',
            name='subject_forbidden_properties',
            field=models.ManyToManyField(
                to='creme_core.CremePropertyType',
                related_name='relationtype_forbidden_set',
                blank=True,
            ),
        ),
    ]
