# Generated by Django 4.1.7 on 2023-03-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creme_core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historyline',
            index=models.Index(fields=['entity_id', '-id'], name='hline__entity_detailview'),
        ),
    ]
