# Generated by Django 4.2.16 on 2024-12-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0159_v2_7__buttonmenuitem_per_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('plural_name', models.CharField(max_length=50, verbose_name='Name (plural)')),
                ('enabled', models.BooleanField(default=False, editable=False)),
                ('deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Custom entity',
                'verbose_name_plural': 'Custom entities',
                'ordering': ('name',),
            },
        ),
    ]
