################################################################################
#
# Copyright (c) 2009-2026 Hybird
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################

# import warnings
from collections.abc import Container, Iterable, Iterator

from django.contrib.contenttypes.models import ContentType
from django.db.models import CharField, Model
from django.db.models import Value as V
from django.db.models.expressions import Func
from django.db.models.functions import Cast, Concat, StrIndex
from django.http import Http404

# def ctype_as_key(ctype: ContentType, /) -> str:
#     "Key is a string like 'my_app.mymodel', which can be serialized/exchanged between DB."
#     warnings.warn(
#         'ctype_as_key() is deprecated; use ContentType.portable_key() instead.',
#         DeprecationWarning
#     )
#
#     return '.'.join(ctype.natural_key())


# def ctype_from_key(ctype_key: str, /) -> ContentType:
#     """Build an instance of ContentType from an exchangeable key.
#     @param ctype_key: can be generated by ctype_as_key().
#     @return A ContentType instance.
#     @raise ValueError if the key is malformed.
#     @raise ContentType.DoesNotExist.
#     """
#     warnings.warn(
#         'ctype_from_key() is deprecated; '
#         'use ContentType.objects.get_by_portable_key() instead.',
#         DeprecationWarning
#     )
#
#     app_label, model_name = ctype_key.split('.', 2)
#
#     return ContentType.objects.get_by_natural_key(app_label=app_label, model=model_name)


# TODO: exception if bad type (see <as_model()>)
def as_ctype(value: ContentType | type[Model] | Model, /) -> ContentType:
    return (
        value
        if isinstance(value, ContentType) else
        ContentType.objects.get_for_model(value)
    )


def as_model(value: ContentType | type[Model] | Model, /) -> type[Model]:
    if isinstance(value, ContentType):
        return value.model_class()

    if isinstance(value, Model):
        return type(value)

    if isinstance(value, type) and issubclass(value, Model):
        return value

    raise TypeError('Type must be ContentType/Model class/Model instance')


def entity_ctypes(app_labels: Container[str] | None = None) -> Iterator[ContentType]:
    """Generator which yields ContentType instances corresponding to registered
     entity models.
    @param app_labels: If None is given, all the registered models are yielded.
           If a container of app labels is given, only models related to these
           apps are yielded.
    """
    from ..registry import creme_registry
    return map(
        ContentType.objects.get_for_model,
        creme_registry.iter_entity_models(app_labels=app_labels),
    )


def get_ctype_or_404(ct_id: int | str) -> ContentType:
    """Retrieve a ContentType by its ID.
    @param ct_id: ID of the wanted ContentType instance (int or string).
    @return: ContentType instance.
    @raise: Http404 Exception if the ContentType does not exist.
    """
    try:
        ct = ContentType.objects.get_fresh_for_id(ct_id)
    except (ValueError, ContentType.DoesNotExist) as e:
        raise Http404(f'No content type with this id: {ct_id}') from e

    return ct


def ctype_choices(ctypes: Iterable[ContentType]) -> list[tuple[int, str]]:
    """ Build a choices list (useful for form ChoiceField for example) for ContentTypes.
    Labels are localized, & choices are sorted by labels.
    @param ctypes: Iterable of ContentTypes.
    @return: A list of tuples.
    """
    from .unicode_collation import collator
    choices = [(ct.id, str(ct)) for ct in ctypes]

    sort_key = collator.sort_key
    choices.sort(key=lambda k: sort_key(k[1]))

    return choices


def CTypeSmartOrder(ctype_fk_name: str, ctypes: Iterable[ContentType] | None = None) -> Func:  # NOQA
    """Returns a Database Function which uses a ForeignKey to ContentType to
    produce an order (int) based on the ContentTypes' labels.

    @param ctype_fk_name: Name of a ForeignKey which belongs to the model
    @param ctypes: ContentTypes instances used to build the internal "order-grid".
           By default, all ContentTypes are used ; it's better to narrow the
           possible choices (to build a smaller grid) if you can.
           E.g. you can use <entity_ctypes()> if the ContentTypes referenced by
           the ForeignKey is always related to an entity model.
    @return A <django.db.models.expressions.Func> object.

    Hint: it can be useful to annotate()+order_by() a query.
          >> CremeEntity.objects.annotate(
                ct_order=CTypeSmartOrder('entity_content'),
            ).order_by('ct_order')
    """
    from .unicode_collation import collator

    ctypes = [*ContentType.objects.all()] if ctypes is None else [*ctypes]
    sort_key = collator.sort_key
    # NB: ContentType.__str__ is hooked in creme_core.apps to be
    #     <str(ct.model_class()._meta.verbose_name)>
    ctypes.sort(key=lambda ct: sort_key(str(ct)))

    # NB: we build a big string with all the ContentType IDs in the correct
    #     order (i.e. ordered by their label -- which is language dependant);
    #     it looks like "[23][4][8]..." so the orders (in this string) of the
    #     IDs (as strings) can be used to order a query.
    #     Notice that we decorate IDs with "[]" to avoid wrong matches
    #     (e.g. ID "1" is found in "21", "[1]" is not found in "[21]").
    return StrIndex(
        # Text in which we search.
        V(''.join(f'[{ct.id}]' for ct in ctypes)),
        # Sub-string
        Concat(V('['), Cast(ctype_fk_name, output_field=CharField()), V(']')),
    )
