# Generated by Django 2.2 on 2019-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgraph',
            name='asc',
            field=models.BooleanField(default=True, editable=False, verbose_name='ASC order'),
        ),
    ]
