# Generated by Django 2.2.11 on 2020-03-19 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0008_v2_2__abscissa_fields_rework02'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportgraph',
            name='days',
        ),
    ]
