# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models

import creme.creme_core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0037_v1_8__empty_json_cells_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filedata', models.FileField(max_length=200, upload_to=b'')),
                ('basename', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('temporary', models.BooleanField(default=True, verbose_name=b'Is temporary?')),
                ('user', creme.creme_core.models.fields.CremeUserForeignKey(null=True, to=settings.AUTH_USER_MODEL, verbose_name=b'Owner user')),
            ],
        ),
    ]
