# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0042_v1_8__set_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='header_filter_search_field',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='modified',
        ),
    ]
