# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0043_v2_0__rm_abstract_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferedmenuitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='PreferedMenuItem',
        ),
    ]
