# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0045_v2_0__rm_portalbrick_app_name_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockportallocation',
            name='app_name',
        ),
    ]
