# Generated by Django 3.2.2 on 2021-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0081_v2_2__global_search_customfields03'),
    ]

    operations = [
        migrations.AddField(
            model_name='cremepropertytype',
            name='enabled',
            field=models.BooleanField(default=True, editable=False, verbose_name='Enabled?'),
        ),
    ]
