# Generated by Django 3.2.12 on 2022-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creme_core', '0109_v2_4__fieldsconfig_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformconfigitem',
            name='json_groups',
            field=models.JSONField(default=list, editable=False),
        ),
    ]
