# Generated by Django 3.2.13 on 2022-09-26 14:51

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creme_core', '0118_v2_4__fileref_extra_data'),
    ]

    operations = [
        UnaccentExtension()
    ]
