BRICK_STATE_HIDE_INACTIVE_USERS  = 'creme_config-hide_inactive_users'
BRICK_STATE_HIDE_DELETED_CFIELDS = 'creme_config-hide_deleted_customfields'
BRICK_STATE_SHOW_CFORMS_DETAILS  = 'creme_config-show_customforms_details'

# Transfer IDs
ID_VERSION = 'version'

ID_ROLES           = 'roles'
ID_MENU            = 'menu'
ID_BUTTONS         = 'buttons'
ID_SEARCH          = 'search'
ID_PROPERTY_TYPES  = 'property_types'
ID_RELATION_TYPES  = 'relation_types'
ID_FIELDS_CONFIG   = 'fields_config'
ID_CUSTOM_FIELDS   = 'custom_fields'
ID_HEADER_FILTERS  = 'header_filters'
ID_ENTITY_FILTERS  = 'entity_filters'
ID_CUSTOM_FORMS    = 'custom_forms'
ID_RTYPE_BRICKS    = 'rtype_bricks'
ID_INSTANCE_BRICKS = 'instance_bricks'
ID_CUSTOM_BRICKS   = 'custom_bricks'
ID_DETAIL_BRICKS   = 'detail_bricks'
ID_HOME_BRICKS     = 'home_bricks'
ID_MYPAGE_BRICKS   = 'mypage_bricks'
ID_CHANNELS        = 'channels'
