# Generated by Django 2.2.16 on 2020-09-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0019_v2_2__task_start_end_duration_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tmp_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
